# Generated by Django 5.1.7 on 2025-03-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('mass', models.FloatField()),
                ('jx', models.FloatField()),
                ('jxy', models.FloatField()),
                ('jxz', models.FloatField()),
                ('jyx', models.FloatField()),
                ('jy', models.FloatField()),
                ('jyz', models.FloatField()),
                ('jzx', models.FloatField()),
                ('jzy', models.FloatField()),
                ('jz', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LoadName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
