# Generated by Django 5.1.7 on 2025-04-09 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['path_id'],
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('roll', models.FloatField()),
                ('pitch', models.FloatField()),
                ('yaw', models.FloatField()),
                ('tool', models.IntegerField()),
                ('figure', models.IntegerField()),
                ('work', models.IntegerField()),
                ('motion', models.CharField()),
                ('cont', models.BooleanField()),
                ('stop', models.BooleanField()),
                ('vel', models.IntegerField()),
                ('acc', models.IntegerField()),
                ('corner', models.IntegerField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='api.path')),
            ],
            options={
                'ordering': ['point_id'],
            },
        ),
    ]
