# Generated by Django 5.1.7 on 2025-06-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='cont',
        ),
        migrations.AddField(
            model_name='point',
            name='ee',
            field=models.CharField(default='Grip'),
            preserve_default=False,
        ),
    ]
