# Generated by Django 5.1.7 on 2025-06-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_point_cont_point_ee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_id', models.IntegerField(unique=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('roll', models.FloatField()),
                ('pitch', models.FloatField()),
                ('yaw', models.FloatField()),
            ],
            options={
                'ordering': ['home_id'],
            },
        ),
    ]
