# Generated by Django 5.1.7 on 2025-04-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_path_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('roll', models.FloatField()),
                ('pitch', models.FloatField()),
                ('yaw', models.FloatField()),
                ('tool', models.IntegerField()),
                ('figure', models.IntegerField()),
                ('work', models.IntegerField()),
            ],
            options={
                'ordering': ['point_id'],
            },
        ),
    ]
