# Generated by Django 5.1.7 on 2025-06-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='pitch',
            new_name='t1',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='roll',
            new_name='t2',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='x',
            new_name='t3',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='y',
            new_name='t4',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='yaw',
            new_name='t5',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='z',
            new_name='t6',
        ),
    ]
