# Generated by Django 5.1.7 on 2025-05-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='path_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.path', to_field='path_id'),
        ),
    ]
