# Generated by Django 5.1.7 on 2025-06-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_pitch_home_t1_rename_roll_home_t2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_id',
        ),
        migrations.AlterField(
            model_name='home',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
