# Generated by Django 5.1.7 on 2025-06-04 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_site_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('new_file', models.BooleanField()),
                ('name_file', models.CharField(max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.site', to_field='site_id')),
            ],
            options={
                'ordering': ['map_id'],
            },
        ),
    ]
