# Generated by Django 5.1.7 on 2025-06-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_home_options_remove_home_home_id_alter_home_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global',
            old_name='pitch',
            new_name='t1',
        ),
        migrations.RenameField(
            model_name='global',
            old_name='roll',
            new_name='t2',
        ),
        migrations.RenameField(
            model_name='global',
            old_name='x',
            new_name='t3',
        ),
        migrations.RenameField(
            model_name='global',
            old_name='y',
            new_name='t4',
        ),
        migrations.RenameField(
            model_name='global',
            old_name='yaw',
            new_name='t5',
        ),
        migrations.RenameField(
            model_name='global',
            old_name='z',
            new_name='t6',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='pitch',
            new_name='t1',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='roll',
            new_name='t2',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='x',
            new_name='t3',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='y',
            new_name='t4',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='yaw',
            new_name='t5',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='z',
            new_name='t6',
        ),
    ]
