# Generated by Django 5.1.7 on 2025-06-25 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_pitch_global_t1_rename_roll_global_t2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aruco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aruco', models.IntegerField()),
                ('task', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('roll', models.FloatField()),
                ('pitch', models.FloatField()),
                ('yaw', models.FloatField()),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aruco_tags', to='api.point')),
            ],
        ),
    ]
