# Generated by Django 5.1.7 on 2025-07-07 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_aruco'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalPose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('yaw', models.FloatField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_tags', to='api.map')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
