# Generated by Django 5.1.7 on 2025-07-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_goalpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalpose',
            name='name',
            field=models.CharField(default='nice'),
            preserve_default=False,
        ),
    ]
