# Generated by Django 5.1.7 on 2025-07-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_goalpose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalpose',
            name='goal_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
