# Generated by Django 5.1.7 on 2025-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='grip',
            field=models.CharField(default='Pick'),
            preserve_default=False,
        ),
    ]
