<?xml version="1.0"?>
<robot name="ammr_main" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="wheels_radius" value="0.162"/>

<!-- RIGHT DRIVE WHEEL LINK-->
    <link
    name="Right_Drive_wheel_Link">
    <inertial>
        <origin
        xyz="-7.63278329429795E-17 -1.11022302462516E-16 -0.00236500745899665"
        rpy="0 0 0" />
        <mass
        value="3.39203243164232" />
        <inertia
        ixx="0.0243089316503053"
        ixy="1.60800968207563E-18"
        ixz="3.26375472339224E-16"
        iyy="0.0243089316503053"
        iyz="-7.7401651668733E-17"
        izz="0.047247796608228" />
    </inertial>
    <visual>
        <origin
        xyz="0 0 0"
        rpy="0 0 0" />
        <geometry>
        <mesh
            filename="file://$(find ammr_mock_components)/meshes/Right_Drive_wheel_Link.STL" />
        </geometry>
        <material
        name="">
            <color rgba="0.929 0.298 0.337 1" />
        </material>
    </visual>
    <collision>
        <origin
        xyz="0 0 0"
        rpy="0 0 0" />
        <geometry>
            <sphere radius="${wheels_radius}"/>
        </geometry>
    </collision>
    </link>
<!-- RIGHT DRIVE WHEEL JOINT-->
    <joint
    name="Right_Drive_wheel_Joint"
    type="continuous">
    <origin
        xyz="-0.034 -0.2056 ${frame_ground_offset + 0.0451499976997314}"
        rpy="${pi/2} 0 0" />
    <parent link ="base_link" />
    <child link="Right_Drive_wheel_Link" />
    <axis
        xyz="0 0 1" />
    </joint>
<!-- LEFT DRIVE WHEEL LINK-->
    <link
    name="Left_Drive_wheel_Link">
    <inertial>
        <origin
        xyz="6.93889390390723E-18 -8.32667268468867E-17 0.00236500745899662"
        rpy="0 0 0" />
        <mass
        value="3.39203243164232" />
        <inertia
        ixx="0.0243089316503053"
        ixy="4.85437810349641E-19"
        ixz="2.48098582544798E-16"
        iyy="0.0243089316503053"
        iyz="1.31831110354224E-16"
        izz="0.047247796608228" />
    </inertial>
    <visual>
        <origin
        xyz="0 0 0"
        rpy="0 0 0" />
        <geometry>
            <mesh filename="file://$(find ammr_mock_components)/meshes/Left_Drive_wheel_Link.STL" />
        </geometry>
        <material
        name="">
            <color rgba="0.929 0.298 0.337 1" />
        </material>
    </visual>
    <collision>
        <origin
        xyz="0 0 0"
        rpy="0 0 0" />
        <geometry>
            <sphere radius="${wheels_radius}"/>
        </geometry>
    </collision>
    </link>
<!-- LEFT DRIVE WHEEL JOINT-->
    <joint
    name="Left_Drive_wheel_Joint"
    type="continuous">
    <origin
        xyz="-0.04 0.2056 ${frame_ground_offset + 0.04515}"
        rpy="1.5707963267949 0 0" />
    <parent
        link="base_link" />
    <child
        link="Left_Drive_wheel_Link" />
    <axis
        xyz="0 0 1" />
    </joint>

</robot>